site_name: Sandbox Docs
repo_url: https://github.com/adlnet/SandboxDocs
site_favicon: favicon.ico
docs_dir : ./docs
theme: readthedocs
use_directory_urls: true
markdown_extensions: [admonition]
pages:
- About: index.md
- Home: Home.md
- For Developers: Developer Guide/Developer-Guide.md
- For Users:
  - FAQ: FAQ.md
  - Using The Editor: User Guide/Using-The-Editor.md
  - Selecting Objects: User Guide/Selecting-Objects.md
  - Lights and Materials: User Guide/Lights and Materials.md
  - Terrain: User Guide/terrain.md
  - Cameras: User Guide/Cameras.md
  - GUI Nodes: User Guide/GUINodes.md
  - Physics: User Guide/Physics.md
  - Particles: User Guide/Particles.md
  - Assets and Models: User Guide/Assets.md
  - Phong Material: User Guide/Phong-Material.md
  - Sharing the Camera View: User Guide/Sharing-the-camera-view.md
  - User Guide: User Guide/User-Guide.md
  - Working with Groups: User Guide/Working with Groups.md
  - Working with Terrain: User Guide/Working with Terrain.md
  - Build a Game: User Guide/build a game.md
- Developer Guide:
  - Installation: Developer Guide/Installation.md
  - Configuration: Developer Guide/Configuration.md
  - Asset Server: Developer Guide/configure 3DR.md
  - Architecture Overview: Developer Guide/Architecture-Overview.md
  - Data Organization: Developer Guide/Data-Organization.md
  - File Organization: Developer Guide/File-Organization.md
  - Development Plans: Developer Guide/Development-Plans.md
  - Sandbox API: Developer Guide/SandboxAPI.md
  - 3rd Party Libraries: Developer Guide/_3rd-Party-Libraries.md
  - Driver Reference: Developer Guide/drivers/Drivers.md
  - Three.js Model: Developer Guide/drivers/Threejsmodel.md
  - Three.js View Driver: Developer Guide/drivers/Threejs-view.md
  - Editor View: Developer Guide/drivers/Editor-view.md
  - Inventory Manager: Developer Guide/editors/InventoryManager.md
  - Primitive Editor: Developer Guide/editors/PrimitiveEditor.md
  - Publisher: Developer Guide/editors/Publisher.md
  - Script Editor: Developer Guide/editors/ScriptEditor.md
  - Selection Editor: Developer Guide/editors/SelectionEditor.md
  - Undo Manager: Developer Guide/editors/UndoManager.md
  - Extending Sandbox: Developer Guide/Extending.md
  - Add a New Camera Mode: Developer Guide/extending/Add-a-new-camera-mode.md
  - Add a New Menu Item: Developer Guide/extending/Add-a-new-menu-item.md
  - Main Toolbar Button: Developer Guide/extending/Main-toolbar-buttons.md
  - Asset Pipeline: Developer Guide/Assets.md
  - Prim and Modifier Pipeline: Developer Guide/Prims-and-Modifiers.md
  - Asset and Server Integration: Developer Guide/Asset-Server-Integration.md
  - Development: Developer Guide/Development.md
  - Particle Systems: Developer Guide/particleSystem.md
  - Cluster Server: Developer Guide/Cluster.md
- Scripting:
  - Introduction to Scripting: Scripting/scripting/ScriptingIntro.md
  - Events: Scripting/scripting/Events.md
  - Behaviors: Scripting/scripting/Behaviors.md
  - Working with Entities: Scripting/scripting/Working with Entities.md
  - Entity Property Reference: Scripting/scripting/Entity Property Reference.md
  - Nodes: Scripting/scripting/Nodes.md
- System APIs:
  - System API: SystemAPI/SystemAPIs.md
  - Audio API: SystemAPI/AudioAPI.md
  - Client API: SystemAPI/ClientAPI.md
  - Communications API: SystemAPI/CommsAPI.md
  - Physics API: SystemAPI/PhysicsAPI.md
  - Transform API: SystemAPI/TransformAPI.md
